### PR TITLE
chore: drop Node.js v4 support from AppVeyor

### PR DESCRIPTION
**Pull request by timbru31**
Part of apache/cordova#72

### Platforms affected

n/a - development

### Motivation and Context

Drops EOL Node.js 4 from CI config. BREAKING CHANGE! :)

### Description

see above.

### Testing

TravisCI and Appveyor test results.

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by janpio** [comment]
Uh, this should get an issue in https://github.com/apache/cordova as a collection for all plugins. Then all the PRs can link to that issue, we can make sure all plugins were taken care of etc. 

Is this already based on something we did for another Cordova repo? (these CI configs should be pretty much copy/paste to all similar repos in the best case)

**Comment by timbru31** [comment]
We had https://github.com/apache/cordova/issues/5, but just for tooling and platforms

**Comment by janpio** [comment]
Yeah, go ahead and create a new one. It's worth to centralize these things, otherwise someone will have to go through all repos in the future and make sure the all use the same config.

**Comment by timbru31** [comment]
There we go: https://github.com/apache/cordova/issues/72

**Comment by janpio** [comment]
Great. See my PR comments on https://github.com/apache/cordova-plugin-statusbar/pull/124/files before you continue.

**Comment by timbru31** [comment]
@janpio - ready for review now

**Comment by timbru31** [comment]
CI passes again, see https://github.com/apache/cordova/issues/72#issuecomment-486007935 - I've used the same matrix as in https://github.com/apache/cordova-paramedic.

**Comment by janpio** [comment]
We have a passing state at paramedic, so now we'll see what happens with the first plugins. https://github.com/apache/cordova-plugin-inappbrowser/pull/465 is the other first try to adapt the configuration from there.

I think you missed the local test for your adaptation here. 
But all the tests passing is nice.

**Comment by timbru31** [comment]
> I think you missed the local test for your adaptation here.
Indeed

**Comment by timbru31** [comment]
Obsolete with #80

**Pull request merged**
