### PR TITLE
CB-13045: Removed android implementation and Updated README

### PR DESCRIPTION
**Pull request by maverickmishra**
The Android webview ( API level 19 and up ) natively supports the W3C spec and hence the android specific implementation can be dropped. 

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Note:
README still lists Android as supported platform for `navigator.vibrate`, `navigator.notification.vibrate` and `navigator.notification.vibrateWithPattern`.

Question:
Does that mean that users of the plugin have to build an if-block to differentiate between iOS and Android to call the W3C spec code for Android?

**Comment by maverickmishra** [comment]
`navigator.notification.vibrate` and `navigator.notification.vibrateWithPattern` are already deprecated for the plugin. To answer your question, usage of `navigator.vibrate` will automatically use the W3C spec for Android and the iOS-specific code from the plugin for iOS.

**Comment by janpio** [comment]
> navigator.notification.vibrate and navigator.notification.vibrateWithPattern are already deprecated for the plugin. 

Ah ok, meaning that this change only _drops_ support for `cancelVibration` where no standard support is available, thus only there the README is changed. Correct?

> To answer your question, usage of navigator.vibrate will automatically use the W3C spec for Android and the iOS-specific code from the plugin for iOS.

Thanks for the clarification. Pays off if the plugins use the future standard APIs ;)

**Comment by macdonst** [comment]
@maverickmishra considering this is a breaking API change and we'll be bumping the version to 3.0.0 we might as well take out `vibrateWithPattern` & `cancelVibration`.

**Comment by maverickmishra** [comment]
Good idea! I'll make the necessary changes now

**Pull request merged**
